### ISSUE TITLE
l0-setup apply overwrites user-provided dockercfg file with empty creds 

### ISSUE THREAD

**Issue by jonathanstallings** [quintilesims/layer0#11]
l0-setup Version: `v0.8.4_darwin`

Description: `l0-setup apply` overwrites user-provided `dockercfg` file with empty creds `{}`.

Steps to Reproduce: 
1) Run `l0-setup apply <prefix>` without an existing `layer0/instances/<prefix>` directory.
2) Enter the requested AWS credentials.
3) When the prompt stops and advises you to add a valid `dockercfg` file to the `layer0/instances/<prefix>`, do so.
4) Enter `yes` to continue.
5) The `layer0/instances/<prefix>/dockercfg` file will be replaced with contents: `{}`.

Relevant docs:
http://docs.xfra.ims.io/setup/install/#optional-part-3-configure-the-dockercfg-file-to-use-a-private-docker-registry

**Comment by diemonster** [comment]
This is due to how we check for an existing `dockercfg` file: https://github.com/quintilesims/layer0/blob/master/setup/context/commands.go#L408 . If the file is placed after the prompt to create one, it will not be rechecked and will instead be overwritten. 

I'd rather not add _another_ prompt to this section if the file is placed. Will mull this workflow over  a bit and get a patch out shortly.

**Comment by jonathanstallings** [comment]
Could we, perhaps, change to the `l0-setup apply` command to accept a path to a valid `dockercfg` file, which would then be copied to the instance directory after validation?

Then the private docker registry user would only have to run `l0-setup apply` once.

In the other case, if users pass an empty path to dockercfg prompt, l0-setup will create an empty dockercfg file, as is the current behavior.

**Comment by diemonster** [comment]
@jonathanstallings I could get behind that, especially using an optional flag for specifying the `dockercfg` path.

i.e. 
`l0-setup apply --dockercfg /path/filename ...`

@zpatrick any preference here?
