### ISSUE TITLE
Investigate L0 performance limit causes

### ISSUE THREAD

**Issue by tribaljack** [quintilesims/layer0#325]
### Expected behavior
No performance cap from proper scaling of services/resources in L0.

### Actual behavior
Hitting some limits.  Theorizing task definition limit hit? need verification. 

- [ ] EOF when listing deploys in stress tests back-to-back without cool off period

Exceptionally long log output should be posted as a gist (https://gist.github.com).

### Steps to reproduce the behavior

Please also include the following if applicable:
l0 v0.10.3

**Comment by jparsons04** [comment]
Here is specifically what I did to reproduce EOF conditions.
I started off with a layer0 instance that was cleaned using flow.sh:
`$ flow.sh delete`

I can confirm that when I use the aws cli to list my task definitions, I get an empty set returned:
```
$ aws ecs list-task-definitions --family-prefix l0-jparsonsdev-job
{
    "taskDefinitionArns": []
}
```

I then ran through iterations of benchmark tests (https://github.com/quintilesims/layer0/blob/5e6e83725fdb2ec9d81cdd2acaaabcc3c6aec5f7/tests/stress/benchmarkstress_test.go) to build up the Task definitions.

Around the point at which I had 650 Task Definitions, I started to see this behavior on Benchmark Tests:
https://gist.github.com/jparsons04/872ecea0fcfbed4a91d5d936fc6ab88a

However, running these same benchmarks at an earlier point in time ran without issue:
https://gist.github.com/jparsons04/a21a4654d2abf152c277bd177cd02f83

However, dismantling the environments (via terraform destroy) would allow me to list deploys. But subsequent attempts to terraform apply through the benchmark tests would cause the EOF to reappear.

At the point I had built up 1274 Task Definitions, I was consistently getting EOFs, even with an otherwise empty layer0 instance:
https://gist.github.com/jparsons04/43c2c363ad7ab9fc046b296bb81a1436

The for loops represent my attempt to `l0 deploy get` on specific wildcard queries, and <freeze> represents when the loop froze for a considerable amount of time. They demonstrate that `l0 deploy list` or `l0 deploy get` when it attempts to retrieve deploys that begin with `job*` have been taking a considerable amount of time.

**Comment by jparsons04** [comment]
This investigation is part of the work to augment the stress testing benchmarks on #232

**Comment by jparsons04** [comment]
With the recent changes that were pulled into the develop branch (https://github.com/quintilesims/layer0/commit/d1e9b1e029e75721453554d94738040be8ed4af5), my investigation mainly focused on running the benchmark test `BenchmarkMaxFamiliesMaxDeploys`, setting DEPLOY_SCALE_MAX to 120 and DEPLOY_FAMILY_SCALE_MAX to 30.

In my testing, it only takes a couple of runs to break the test, specifically generating the EOF condition when attempting to ListDeploys:

https://gist.github.com/jparsons04/90a12a3e4460039ecf1eb32337b194d1

I was monitoring my l0 api's CloudWatch logs at the time ListDeploys was being executed and found the following events recorded at the time:

```
2017-09-07 18:22:51 [Main] INFO : request GET /deploy/ (200) 30.338196516s
2017-09-07 18:23:44 [Main] INFO : request GET /deploy/ (200) 50.521704365s
2017-09-07 18:23:47 [Main] INFO : request GET /deploy/ (200) 1m2.412040273s
2017-09-07 18:24:30 [Main] INFO : request GET /deploy/ (200) 44.72531413s
```
30-60 seconds to execute ListDeploys seems to be a really long time.

Also it should be noted that while my l0 instance was in this state, executing `l0 deploy list` returned EOF.

I will be curious to see how the API refactoring might change the handling of this benchmark test and would look to execute this same benchmark test for comparison when it is ready.
