### ISSUE TITLE
Unclear error message when missing aws-access-key

### ISSUE THREAD

**Issue by nehayward** [quintilesims/layer0#361]
### Expected behavior
After following [layer0 install](http://layer0.ims.io/setup/install/) and creating an Access AWS Key and entering it into the l0-setup, you still can't access aws without having aws-cli installed. This is because you are missing the aws-access key environment variables. Although it can be set with `l0-setup init --aws-access-key=...` it's not clear in the initial setup. 

### Actual behavior
After finishing the setup you get this message. I believe there should be at least a warning or error message and message to install aws-cli. This should also be added to the initial prerequisites [here](https://github.com/quintilesims/layer0/blob/develop/docs-src/docs/setup/install.md) too for the install docs. 

`No valid AWS credentials found. Please specify an AWS access key and secret key using their corresponding flags or environment variables`
<img width="1005" alt="error" src="https://user-images.githubusercontent.com/6733030/30864112-5f2c6bd0-a298-11e7-9d6f-d4fe00f2e140.png">

The error message occurs [here](https://github.com/quintilesims/layer0/blob/c815bb05a3a0945b9b853c8df66acc9b9c99feda/setup/command/aws.go#L47-L56) 

### Steps to reproduce the behavior
Delete aws-cli and run l0-setup init (instance-name)

- Layer0 Setup version v0.10.3

**Comment by jparsons04** [comment]
There are a couple of areas in the code I feel need to be looked at.

1) It seems to me that the logic of `newAWSProviderHelper` needs to be reexamined, which is invoked during the [apply](https://github.com/quintilesims/layer0/blob/develop/setup/command/apply.go#L36) phase:

```
func (f *CommandFactory) newAWSProviderHelper(c *cli.Context) (*aws.Provider, error) {
     // use default credentials and region settings
     config := defaults.Get().Config
     
     // use static credentials if passed in by the user
     accessKey := c.String("aws-access-key")
     secretKey := c.String("aws-secret-key") 
     if accessKey != "" && secretKey != "" {
         staticCreds := credentials.NewStaticCredentials(accessKey, secretKey, "")
         config.WithCredentials(staticCreds)
     } else {
         logrus.Debugf("aws-access-key or aws-secret-key was not specified. Using default credentials")
     }
 
     // ensure credentials are available
     if _, err := config.Credentials.Get(); err != nil {
         if err, ok := err.(awserr.Error); ok && err.Code() == "NoCredentialProviders" {
             text := "No valid AWS credentials found. Please specify an AWS access key and secret key using "
             text += "their corresponding flags or environment variables"
             return nil, fmt.Errorf(text)
         }
 
         return nil, err
     }
```

If `accessKey` and `secretKey` are not provided as a parameter to `l0-setup init`, and the credentials are not otherwise available through the AWS CLI, default credentials are used (which are anonymous credentials, see [here](https://github.com/quintilesims/layer0/blob/develop/vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go#L55)). But the default credentials can't reliably access AWS in order to interact with a l0 instance.

2) I feel like either `Init()` (`setup/instance/init.go`) needs to be modified to enforce valid AWS credentials up front or we keep `aws-access-key` and `aws-secret-key` optional and enforce the credential check during the instance's `Apply()` (`setup/instance/apply.go`) phase.

I also concur that the documentation should be clearer about the upfront requirements for this issue.

**Comment by diemonster** [comment]
@nehayward is this task completed?
