### ISSUE TITLE
Container exit codes should be non-0 when hitting "CannotPullContainerError"

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/layer0#389]
### Expected behavior
A task's exit code should be non-zero when a  `CannotPullContainerError` error occurs. 

### Actual behavior
When tasks get a `CannotPullContainerError`, the associated exit code is 0 (since the task never started). 
```
{
     "container_name": "foo",
     "exit_code": 0,
    "last_status": "STOPPED",
    "reason": "CannotPullContainerError: Error: image foo/foo not found"
}
```

**Comment by diemonster** [comment]
Should we be fixing specifically to errors around `CannotPullContainer`? It seems like any case where we get an exit code of 0 and `last_status` of `STOPPED` would qualify for Layer0 presenting the exit code as != 0.

**Comment by diemonster** [comment]
In testing, I noticed some additional behavior we should consider fixing. 

For one, `CannotPullContainerError` doesn't actually return an exit code, which is why we return 0. That's easy enough to fix, however we're oddly handling other non-zero errors for containers. For example, I created a task def with a container's `COMMAND` that would intentionally return a `1` exit code (e.g. `cat file`). It returned as `1` via the AWS ECS Console, but we still return "COMPLETED" via Layer0. 

It seems to we need another column of information that gives users' the container's exit code (or lack thereof). Otherwise, I'm not clear on what we're really telling users via the "STATUS" column other than the task was processed by the ECS API.

**Comment by zpatrick** [comment]
I'm not seeing any unintended behavior in the first paragraph. There is already an `exit_code` field in the `Container` model in the `api-refactor` branch.

**Comment by diemonster** [comment]
Will address UX issue here https://github.com/quintilesims/layer0/issues/508

**Comment by tribaljack** [comment]
fixed, closing
