### ISSUE TITLE
Validate() on Request models should error when required fields have zero-values

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/layer0#530]
Currently, if a required field in a request model has a default value, we allow that field to be a 0-value and use the default value where necessary. This isn't a great solution because it requires one to know exactly which fields are and aren't checked during the `RequestModel.Validate()` function. 
It would be better to require that all required fields in a request model be, well, required.

**Comment by nehayward** [comment]
What if we kept the defaults still,  but just let the user know if the defaults are being used. I think there are certain cases where defaults make user experience better. For example most users will be using the new dynamic type by default, we can let them know that the default is being used, so that as you said the users doesn't have to guess/know which fields are checked.

**Comment by zpatrick** [comment]
What you are describing is the current implementation. To be clear, I'm not proposing we remove defaults, just that we explicitly disallow required fields from being empty. I don't expect this to be a UX change (unless users are making calls directly to our API without required field being set, which I'm fairly confident doesn't happen), as much at it is an internal change where we can have a more concrete contract of where/how request validation happens.

**Comment by nehayward** [comment]
👍  I just wanted to clarify and make sure we were on the same page.
