### ISSUE TITLE
l0-setup only checks for dockercfg

### ISSUE THREAD

**Issue by diemonster** [quintilesims/layer0#55]
Versions of docker since April 2015 automatically use a new file format, 'config.json':
http://stackoverflow.com/questions/35519072/docker-config-json-vs-dockercfg

We need to patch l0-setup so that it can use either `dockercfg` or `config.json`

**Comment by jonathanstallings** [comment]
Will do. Question: If neither type of config file (`dockercfg` or `config.json`) is provided by user, which type do we want to create as a default?

**Comment by zpatrick** [comment]
We use the "dockercfg Authentication Format" described [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html). 
Note that those docs are actually wrong on this part:
```
$ cat ~/.docker/config.json
{"https://index.docker.io/v1/":{"auth":"zq212MzEXAMPLE7o6T25Dk0i","email":"email@example.com"}}
```

:point_up: That's in `.dockercfg` format, not a `config.json` format. 
The `config.json` format has an`"auths"` field, it would look like:
```
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "zq212MzEXAMPLE7o6T25Dk0i",
                        "email": "email@example.com"
                }
        }
}
```

So we would want to transform anything in `config.json` format to `.dockercfg` format. 

**...However** 
I don't think anyone has actually tested what happens if you just pass in a `config.json`. There's a chance it may work as is, in which case we could just close this issue. Probably worth checking out.

**Comment by diemonster** [comment]
If you just copy a `config.json` in place of a `dockercfg`, everything seems to work just fine

**Comment by jonathanstallings** [comment]
Thanks, both. Given the above, I've made a very small change that advises the user that they may pass a `config.json` format file to the `--dockercfg` flag.

**Comment by zpatrick** [comment]
@diemonster did you try with a new environment that pulled from a private repo? Running `l0-setup apply` and using an environment that already existed wouldn't have pulled the new docker config file.

**Comment by diemonster** [comment]
@zpatrick I came across this issue specifically when needing `push` access to the quintilesims/l0-api Dockerhub repo. So while it was a public repo, I required creds to push as part of CI. As such, my workflow when discovering the issue was: 
- `docker login -u username -p password`
- `l0-setup apply smoketest`
- spawn a new subshell or a new container
- `l0-setup restore smoketest`

At this point, I get a notification that the `dockercfg` file was not restored.

**Comment by jonathanstallings** [comment]
Thanks, @diemonster. Those are helpful details.

**Comment by zpatrick** [comment]
I just tested this, using the `config.json` format does not work in pulling from private repos. 
Transforming `config.json` into `.dockercfg` format needs to be implemented.

**Comment by jonathanstallings** [comment]
Thanks @zpatrick.
